language: python
python:
  - "2.7"
# command to install dependencies
sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt
# command to run tests

script:
  - docker ps
  - docker ps | grep -q friendlyhello
  - ./init.sh
  - py.test # or py.test for Python versions 3.5 and below
  - curl http://localhost:4000
  - curl http://localhost:80
