language: python
python:
  - "2.7"
# command to install dependencies
sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt
# command to run tests

script:
  - docker build -t friendlyhello .
  - docker run -p 4000:80 friendlyhello

  # - docker-compose -f docker-compose.yml build
  # - docker-compose -f docker-compose.yml up -d
  - docker ps
  - docker ps -a
  - curl http://localhost:4000
