language: python
python:
  - "2.7"
# command to install dependencies
sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt
# command to run tests

script:
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml up -d
  - docker ps
  - docker ps -a
  - docker inspect --format '{{ .NetworkSettings.IPAddress }}' travis101_web_1
  - curl http://localhost:80
