language: python
python:
  - "2.7"
# command to install dependencies
sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt
# command to run tests

script:
  - docker build -t friendlyhello .
  - docker images
  - docker run -d -p 4000:80 friendlyhello
  # - ./init.sh
  # - py.test # or py.test for Python versions 3.5 and below
  # - docker container ls
  - docker ps
  - docker ps -a
  # - docker ps | grep -q friendlyhello
  - docker ps -a | grep friendlyhello | awk '{print $14}'
  - docker ps -a | grep friendlyhello | awk '{print $15}'
  - docker ps -a | grep friendlyhello | awk '{print $16}'
  - docker ps -a | grep friendlyhello | awk '{print $17}'
  - docker ps -a | grep friendlyhello | awk '{print $18}'
  - docker inspect --format '{{ .NetworkSettings.IPAddress }}' docker ps -a | grep friendlyhello | awk '{print $14}'
  - curl http://localhost:4000
  # - curl http://localhost:8080
